### PR TITLE
Header name fix

### LINKED ISSUE #1: Issue with HTTP Header Name regex
Original: https://github.com/github/markup/issues/1229

I've found an issue in HTTP headers, where numbers are not interpreted correctly.

I think the issue is [here](https://github.com/samsalisbury/Sublime-HTTP/blob/0099998617eb784fa27d8a47e289058d9a6307ab/httpspec.YAML-tmLanguage#L32). From the RFC2616, we can see that a header is defined a `token: <some field>`, and `token` is defined as `1*<any CHAR except CTLs or separators>`.

As I understand it, the regex should then be something like `^([^\(\)\<\>@,;:\\\"\{\} \t\0x00-\0x1F\0x7F]+\:)\s(.*)$`

This matches all characters except the CTL's and Seperators defined:
* Seperators: `(`, `)`, `<`, `>`, `@`, `,`, `;`, `:`, `\` `"`, `/`, `[`, `]`, `?`, `=`, `{`, `}`, ` `, `\t`
* CTL's: `\0x00-\0x1F`, `\0x7F` (any US-ASCII control character (octets 0 - 31) and DEL (127))

Links
* https://tools.ietf.org/html/rfc2616.html#section-4.2 <-- On headers
* https://tools.ietf.org/html/rfc2616.html#section-2.2 <-- On Tokens

And should the Colon be part of the headername?

### PR DESCRIPTION
**Pull request by kbjr**
Fixes #1

**Note**: This one is a more complicated regex update, and I haven't yet had a chance to actually test this in a real editor. I'm _fairly_ sure the regex is correct, but might want to hold on this one until it can get tested. I'll try and do that some time this week, if I can remember how to side-load extensions in VS Code....

### CODE REVIEW

**Comment by samsalisbury** [comment]
Thanks for all your contributions @kbjr!  Would you be interested in taking over maintaining this repository as it's not something I have an active interest in at the moment. I'd be happy to make you a maintainer if you want. (I've tried moving this repository before, but it broke some stuff for GitHub so I ended up moving it back.)

**Comment by kbjr** [comment]
I have my own fair share of projects to neglect, so I can't really promise to be the most active long-term maintainer, but I'm certainly happy to help out where I can if that's something you're looking for.

**Comment by kbjr** [comment]
Okay, got it loaded into VSCode and tested it out.

image

I ended up needing to make some adjustments for the HTTP/x prefix as well once I got it running, and I noticed that the list of method names in the xml file and the yaml file were out of sync, so I copied the more extensive list from the xml file over to the yaml file.

**Comment by samsalisbury** [comment]
> I have my own fair share of projects to neglect, so I can't really promise to be the most active long-term maintainer, but I'm certainly happy to help out where I can if that's something you're looking for.

OK, thank you, I'll keep you in mind if I need help in the future then :)

**Pull request merged**
